node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "echo 'testabc1'"
      } else {
         bat(/echo 'testabc1'/)
      }
   }
   stage('Results') {
     if (isUnix()) {
            sh "echo 'doneabc1'"
         } else {
            bat(/echo 'doneabc1'/)
         }
   }
}