node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/jglick/simple-maven-project-with-tests.git'
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         sh "echo 'testabc'"
      } else {
         bat(/echo 'testabc'/)
      }
   }
   stage('Results') {
     if (isUnix()) {
            sh "echo 'doneabc'"
         } else {
            bat(/echo 'doneabc'/)
         }
   }
}