# Use postgres/example user/password credentials
version: '2.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            DB_HOST: 127.0.0.1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lme
        ports:
            - 5432:5432
        expose:
            - 5432