version: '3'
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
    #- --defaultentrypoints=http,https
    - --api
    #- --api.entrypoint="api"
    - --api.dashboard=true
    - --debug=true
    - --docker
    - --docker.watch
    - --retry.attempts=3
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './traefik/traefik.toml:/traefik.toml'
    labels:
      traefik.backend: "traefik"
      traefik.enable: true
      traefik.port: 8080
    networks:
    - proxy

networks:
  proxy:
    external: true