# Unauthorized developer compose
# Expose the FACEBOOK_PROXY_PORT only for a secured container
version: '2.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            DB_HOST: 127.0.0.1
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lme
        ports:
            - 5432:5432
        expose:
            - 5432
    lme:
        links:
            - db
        environment:
                EXPOSED_AUTHENTICATION_PORT: 8091
                INTERNAL_PROXY_PORT: 7081
                DOMAIN: localhost
                ENV: debug
                ENABLED_MODELS: 'KSP'
                FIGURE_DB_STRING: postgresql://postgres:postgres@db:5432/lme
        build: .
        image: ksp:0.0.10
        restart: always
        ports:
            - 80:7081
        expose:
            - 80