# Use postgres/example user/password credentials
version: '3.5'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      DB_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lme
    ports:
    - 5432:5432
    expose:
    - 5432

networks:
  default:
    name: database
    driver: bridge
    external: true