# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres
        restart: always
        network_mode: host
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lme
        ports:
            - 5432:5432
        expose:
            - 5432
    lme:
        links:
            - db
        environment:
                ENV: debug
                FIGURE_DB_STRING: postgresql://postgres:postgres@db:5432/lme
        build: .
        image: lme:1.0.16
        restart: always
        ports:
            - 8080:8080
            - 8082:8082
            - 8083:8083
            - 8084:8084
        expose:
            - 8080
            - 8082
            - 8083
            - 8084