version: '3.5'
services:
  ide:
    image: michaelbakker1986/lme_platform:0.1.27
    container_name: lme_platform
    environment:
      ENV: debug
      HOST: appmodel.org
      FIGURE_DB_STRING: postgresql://postgres:postgres@database:5432/lme
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      traefik.frontend.rule: PathPrefix:/ide/0.1.2/;PathPrefixStrip:/ide/0.1.2/
      traefik.docker.network: proxy
      traefik.port: 7081
    networks:
    - proxy
    - database
    - internal

networks:
  proxy:
    external: true
  internal:
    external: false
  database:
    name: database
    driver: bridge
    external: true