
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie Model Revisie v4.8
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 116
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Wed Nov 20 14:40:16 UTC+0100 2013
 */ 


drop table EXPORT_REVISIE;
create table EXPORT_REVISIE(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_REVISIE add Q_ROOT number default null; 
alter table EXPORT_REVISIE add Q_STATUS number default null; 
alter table EXPORT_REVISIE add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_REVISIE add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_REVISIE add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_REVISIE add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_REVISIE add FPS_VAR_Woonplaats varchar2(256 char) default null; 
alter table EXPORT_REVISIE add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIE add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIE add NaamAanvrager varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Relatienummer varchar2(256 char) default null; 
alter table EXPORT_REVISIE add KvKnummer varchar2(256 char) default null; 
alter table EXPORT_REVISIE add GRIDID varchar2(256 char) default null; 
alter table EXPORT_REVISIE add OprichtingsdatumKvK date default null; 
alter table EXPORT_REVISIE add KlantINGSinds date default null; 
alter table EXPORT_REVISIE add LOO number default null; 
alter table EXPORT_REVISIE add KFRNummer varchar2(256 char) default null; 
alter table EXPORT_REVISIE add SBF number default null; 
alter table EXPORT_REVISIE add Branche varchar2(256 char) default null; 
alter table EXPORT_REVISIE add LinkNaarMeerInformatie varchar2(256 char) default null; 
alter table EXPORT_REVISIE add NaamAanvrager2 varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Relatienummer2 varchar2(256 char) default null; 
alter table EXPORT_REVISIE add NaamAanvrager3 varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Relatienummer3 varchar2(256 char) default null; 
alter table EXPORT_REVISIE add OmzetVorigMnd number default null; 
alter table EXPORT_REVISIE add OmzetVorig3Mnd number default null; 
alter table EXPORT_REVISIE add OmzetVorig6Mnd number default null; 
alter table EXPORT_REVISIE add OmzetVorig12Mnd number default null; 
alter table EXPORT_REVISIE add LimietVorigMnd number default null; 
alter table EXPORT_REVISIE add LimietVorig2Mnd number default null; 
alter table EXPORT_REVISIE add OverstandHuidig number default null; 
alter table EXPORT_REVISIE add OverstandAantalDagen number default null; 
alter table EXPORT_REVISIE add OverstandVorigHalfJaar number default null; 
alter table EXPORT_REVISIE add Rating varchar2(256 char) default null; 
alter table EXPORT_REVISIE add RatingVorigJaar varchar2(256 char) default null; 
alter table EXPORT_REVISIE add RevisieDatumKOS date default null; 
alter table EXPORT_REVISIE add Signaal1 number default null; 
alter table EXPORT_REVISIE add Signaal2 number default null; 
alter table EXPORT_REVISIE add Signaal3 number default null; 
alter table EXPORT_REVISIE add Signaal4 number default null; 
alter table EXPORT_REVISIE add Signaal5 number default null; 
alter table EXPORT_REVISIE add Signaal6 number default null; 
alter table EXPORT_REVISIE add Signaal7 number default null; 
alter table EXPORT_REVISIE add Signaal8 number default null; 
alter table EXPORT_REVISIE add Signaal9 number default null; 
alter table EXPORT_REVISIE add Signaal10 number default null; 
alter table EXPORT_REVISIE add Faillissement number default null; 
alter table EXPORT_REVISIE add RechtsvormGewijzigd number default null; 
alter table EXPORT_REVISIE add RecenteCijfers number default null; 
alter table EXPORT_REVISIE add RecentGespreksverslag number default null; 
alter table EXPORT_REVISIE add VoldoendeCashflow number default null; 
alter table EXPORT_REVISIE add NettoResultaat number default null; 
alter table EXPORT_REVISIE add PriveOnttrekking number default null; 
alter table EXPORT_REVISIE add Afschrijvingen number default null; 
alter table EXPORT_REVISIE add OperCashflow number default null; 
alter table EXPORT_REVISIE add Aflossingen number default null; 
alter table EXPORT_REVISIE add Vervangingsinvesteringen number default null; 
alter table EXPORT_REVISIE add Dividenduitkeringen number default null; 
alter table EXPORT_REVISIE add Overig number default null; 
alter table EXPORT_REVISIE add NettoCashflow number default null; 
alter table EXPORT_REVISIE add DEBT number default null; 
alter table EXPORT_REVISIE add EBITDA number default null; 
alter table EXPORT_REVISIE add DSCR number default null; 
alter table EXPORT_REVISIE add ICR number default null; 
alter table EXPORT_REVISIE add CAPEX number default null; 
alter table EXPORT_REVISIE add VoldoetAanPolicyPaper number default null; 
alter table EXPORT_REVISIE add AfwijkingVoorwaarden number default null; 
alter table EXPORT_REVISIE add ZijnErVeranderingen number default null; 
alter table EXPORT_REVISIE add VeranderingenManagement number default null; 
alter table EXPORT_REVISIE add OnderliggendProbleemPerformanc number default null; 
alter table EXPORT_REVISIE add StructuurRisico number default null; 
alter table EXPORT_REVISIE add Organogram number default null; 
alter table EXPORT_REVISIE add FinancialStatements number default null; 
alter table EXPORT_REVISIE add Actie1 number default null; 
alter table EXPORT_REVISIE add Actie2 number default null; 
alter table EXPORT_REVISIE add Actie3 number default null; 
alter table EXPORT_REVISIE add Actie4 number default null; 
alter table EXPORT_REVISIE add Actie5 number default null; 
alter table EXPORT_REVISIE add Actie6 number default null; 
alter table EXPORT_REVISIE add Actie7 number default null; 
alter table EXPORT_REVISIE add Actie8 number default null; 
alter table EXPORT_REVISIE add Actie9 number default null; 
alter table EXPORT_REVISIE add Actie11 number default null; 
alter table EXPORT_REVISIE add Actie13 number default null; 
alter table EXPORT_REVISIE add Actie14 number default null; 
alter table EXPORT_REVISIE add Actie15 number default null; 
alter table EXPORT_REVISIE add Actie16 number default null; 
alter table EXPORT_REVISIE add Actie16Omschrijving varchar2(256 char) default null; 
alter table EXPORT_REVISIE add IBReden varchar2(256 char) default null; 
alter table EXPORT_REVISIE add IBVervolgActies varchar2(256 char) default null; 
alter table EXPORT_REVISIE add IBDekking varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Conclusie varchar2(256 char) default null; 
alter table EXPORT_REVISIE add Actie15Keuze number default null; 
alter table EXPORT_REVISIE add DekkingswaardeKredietABS number default null; 
alter table EXPORT_REVISIE add DekkingswaardeKrediet number default null; 
alter table EXPORT_REVISIE add EWSSignaal01 number default null; 
alter table EXPORT_REVISIE add EWSSignaal02 number default null; 
alter table EXPORT_REVISIE add EWSSignaal03 number default null; 
alter table EXPORT_REVISIE add EWSSignaal04 number default null; 
alter table EXPORT_REVISIE add EWSSignaal05 number default null; 
alter table EXPORT_REVISIE add EWSSignaal06 number default null; 
alter table EXPORT_REVISIE add EWSSignaal07 number default null; 
alter table EXPORT_REVISIE add EWSSignaal08 number default null; 
alter table EXPORT_REVISIE add EWSSignaal09 number default null; 
alter table EXPORT_REVISIE add EWSSignaal10 number default null; 
alter table EXPORT_REVISIE add EWSSignaal11 number default null; 
alter table EXPORT_REVISIE add EWSRisicoSignaal number default null; 
alter table EXPORT_REVISIE add CashflowBerekeningGewenst number default null; 

COMMIT;
    
