
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie Model REVISIEGBI v5.11
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 108
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Tue Feb 25 2014 16:34:00 GMT+0100 (W. Europe Standard Time)
 */ 


drop table EXPORT_REVISIEGBI;
create table EXPORT_REVISIEGBI(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_REVISIEGBI add Q_ROOT number default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS number default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add FPS_VAR_Woonplaats varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add NaamAanvrager varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Relatienummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add KvKnummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add GRIDID varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add OprichtingsdatumKvK date default null; 
alter table EXPORT_REVISIEGBI add KlantINGSinds date default null; 
alter table EXPORT_REVISIEGBI add LOO number default null; 
alter table EXPORT_REVISIEGBI add KFRNummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add SBF number default null; 
alter table EXPORT_REVISIEGBI add Branche varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add LinkNaarMeerInformatie varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add NaamAanvrager2 varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Relatienummer2 varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add NaamAanvrager3 varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Relatienummer3 varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add OmzetVorig12Mnd number default null; 
alter table EXPORT_REVISIEGBI add OverstandHuidig number default null; 
alter table EXPORT_REVISIEGBI add OverstandAantalDagen number default null; 
alter table EXPORT_REVISIEGBI add OverstandVorigHalfJaar number default null; 
alter table EXPORT_REVISIEGBI add Rating varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add RatingVorigJaar varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add RevisieDatumKOS date default null; 
alter table EXPORT_REVISIEGBI add Faillissement number default null; 
alter table EXPORT_REVISIEGBI add RechtsvormGewijzigd number default null; 
alter table EXPORT_REVISIEGBI add RecenteCijfers number default null; 
alter table EXPORT_REVISIEGBI add RecentGespreksverslag number default null; 
alter table EXPORT_REVISIEGBI add VoldoendeCashflow number default null; 
alter table EXPORT_REVISIEGBI add NettoResultaat number default null; 
alter table EXPORT_REVISIEGBI add PriveOnttrekking number default null; 
alter table EXPORT_REVISIEGBI add Afschrijvingen number default null; 
alter table EXPORT_REVISIEGBI add OperCashflow number default null; 
alter table EXPORT_REVISIEGBI add Aflossingen number default null; 
alter table EXPORT_REVISIEGBI add Vervangingsinvesteringen number default null; 
alter table EXPORT_REVISIEGBI add Dividenduitkeringen number default null; 
alter table EXPORT_REVISIEGBI add Overig number default null; 
alter table EXPORT_REVISIEGBI add NettoCashflow number default null; 
alter table EXPORT_REVISIEGBI add DEBT number default null; 
alter table EXPORT_REVISIEGBI add EBITDA number default null; 
alter table EXPORT_REVISIEGBI add DSCR number default null; 
alter table EXPORT_REVISIEGBI add ICR number default null; 
alter table EXPORT_REVISIEGBI add CAPEX number default null; 
alter table EXPORT_REVISIEGBI add VoldoetAanPolicyPaper number default null; 
alter table EXPORT_REVISIEGBI add AfwijkingVoorwaarden number default null; 
alter table EXPORT_REVISIEGBI add ZijnErVeranderingen number default null; 
alter table EXPORT_REVISIEGBI add VeranderingenManagement number default null; 
alter table EXPORT_REVISIEGBI add OnderliggendProbleemPerformanc number default null; 
alter table EXPORT_REVISIEGBI add StructuurRisico number default null; 
alter table EXPORT_REVISIEGBI add Organogram number default null; 
alter table EXPORT_REVISIEGBI add FinancialStatements number default null; 
alter table EXPORT_REVISIEGBI add Actie1 number default null; 
alter table EXPORT_REVISIEGBI add Actie2 number default null; 
alter table EXPORT_REVISIEGBI add Actie3 number default null; 
alter table EXPORT_REVISIEGBI add Actie4 number default null; 
alter table EXPORT_REVISIEGBI add Actie5 number default null; 
alter table EXPORT_REVISIEGBI add Actie6 number default null; 
alter table EXPORT_REVISIEGBI add Actie7 number default null; 
alter table EXPORT_REVISIEGBI add Actie8 number default null; 
alter table EXPORT_REVISIEGBI add Actie9 number default null; 
alter table EXPORT_REVISIEGBI add Actie11 number default null; 
alter table EXPORT_REVISIEGBI add Actie13 number default null; 
alter table EXPORT_REVISIEGBI add Actie14 number default null; 
alter table EXPORT_REVISIEGBI add Actie15 number default null; 
alter table EXPORT_REVISIEGBI add Actie16 number default null; 
alter table EXPORT_REVISIEGBI add Actie16Omschrijving varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add IBReden varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add IBVervolgActies varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add IBDekking varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Conclusie varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add Actie15Keuze number default null; 
alter table EXPORT_REVISIEGBI add DekkingswaardeKredietABS number default null; 
alter table EXPORT_REVISIEGBI add DekkingswaardeKrediet number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal01 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal02 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal03 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal04 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal05 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal06 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal07 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal08 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal09 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal10 number default null; 
alter table EXPORT_REVISIEGBI add EWSSignaal11 number default null; 
alter table EXPORT_REVISIEGBI add EWSRisicoSignaal number default null; 
alter table EXPORT_REVISIEGBI add CashflowBerekeningGewenst number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_prioriteits_cluster varchar2(256 char) default null; 
alter table EXPORT_REVISIEGBI add IMPORT_pdscore number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_net_exposure number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_trendinrevenue number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_disp number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_trendinoverdue number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_ratinggetal_mm_num number default null; 

COMMIT;
    
