version: '2'
services:
  HUIS-0.3:
    image: 'michaelbakker1986/huis:0.3'
    container_name: HUIS-0.3
    environment:
      ENV: debug
      ENABLED_MODELS: HUIS
      FIGURE_DB_STRING: 'postgresql://postgres:postgres@database:5432/lme'
      HOST: 127.0.0.1
      RESOURCES_PATH: resources
      MODEL_VERSION: '0.3'
      DATA_API_PORT: 80
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'PathPrefix:/HUIS/0.3/;PathPrefixStrip:/HUIS/0.3/'
      traefik.docker.network: proxy
      traefik.port: 80
    networks:
      - internal
      - database
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
  database:
    external: true
