version: '2'
services:
  KSP2-0.9:
    image: 'michaelbakker1986/ksp2:0.9'
    container_name: KSP2-0.9
    environment:
      ENV: debug
      ENABLED_MODELS: KSP2
      FIGURE_DB_STRING: 'postgresql://postgres:postgres@database:5432/lme'
      HOST: 127.0.0.1
      RESOURCES_PATH: resources
      MODEL_VERSION: '0.9'
      DATA_API_PORT: 80
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host:appmodel.org;PathPrefix:/KSP2/0.9/;PathPrefixStrip:/KSP2/0.9/'
      traefik.docker.network: proxy
      traefik.port: 80
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
