version: '2'
services:
  SCORECARDTESTMODEL-0.2:
    image: 'michaelbakker1986/scorecardtestmodel:0.2'
    container_name: SCORECARDTESTMODEL-0.2
    environment:
      ENV: debug
      ENABLED_MODELS: SCORECARDTESTMODEL
      FIGURE_DB_STRING: 'postgresql://postgres:postgres@database:5432/lme'
      HOST: 127.0.0.1
      RESOURCES_PATH: resources
      MODEL_VERSION: '0.2'
      DATA_API_PORT: 80
    labels:
      traefik.enable: true
      traefik.frontend.rule: >-
        Host:appmodel.org;PathPrefix:/SCORECARDTESTMODEL/0.2/;PathPrefixStrip:/SCORECARDTESTMODEL/0.2/
      traefik.docker.network: proxy
      traefik.port: 80
    networks:
      - internal
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: false
