version: '2'
services:
  reverse-proxy:
    image: traefik
    command: '--api --docker'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  whoami:
    image: 'emilevauge/whoami:latest'
    labels:
      - 'traefik.frontend.rule=Host:lme.appmodel.org'
      - 'traefik.frontend.rule=Path:/whoami/latest'
  ksp:
    image: 'michaelbakker1986/ksp:0.17'
    labels:
      - 'traefik.frontend.rule=Host:lme.appmodel.org'
      - 'traefik.frontend.rule=Path:/ksp/0.17'
