version: '3'
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
    - --api
    - --docker
    - --docker.watch
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './traefik.toml:/traefik.toml'
    labels:
      traefik.backend: "traefik"
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: "Host:lvh.me"
    networks:
    - proxy

networks:
  proxy:
    external: true