version: '3'
services:
  ide:
    image: michaelbakker1986/lme_platform:0.1.2
    container_name: lme_platform
    environment:
      FIGURE_DB_STRING: postgresql://postgres:postgres@database:5432/lme
    labels:
      traefik.frontend.rule: Host:appmodel.org;PathPrefix:/ide/0.1.2/;PathPrefixStrip:/ide/0.1.2/
      traefik.docker.network: proxy
      traefik.port: 7081
    networks:
    - proxy
    - internal

networks:
  proxy:
    external: true
  internal:
    external: false