# Use postgres/example user/password credentials
version: '2.0'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      DB_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lme
    labels:
      traefik.enable: false
      traefik.port: 5432
    networks:
    - internal

networks:
  internal:
    external: false