version: '3'
services:
  ksp2:
    image: 'michaelbakker1986/ksp2:0.20'
    container_name: ksp2_0.20
    environment:
      ENV: debug
      ENABLED_MODELS: KSP2
      FIGURE_DB_STRING: postgresql://postgres:postgres@database:5432/lme
      HOST: appmodel.org
      RESOURCES_PATH: resources
      MODEL_VERSION: 0.20
      DATA_API_PORT: 80
    labels:
      traefik.enable: true
      traefik.backend: ksp2
      traefik.frontend.rule: Host:appmodel.org;PathPrefix:/ksp2/0.20/;PathPrefixStrip:/ksp2/0.20/
      traefik.docker.network: proxy
      traefik.port: 80
    networks:
    - internal
    - proxy

networks:
  proxy:
    external: true
  internal:
    external: false