# API definition
# Warning: Enabling API will expose Traefik's configuration.
# It is not recommended in production,
# unless secured by authentication and authorizations
#defaultEntryPoints = ["http", "https"]

[entryPoints]
 # [entryPoints.http]
 # address = ":80"
 #   [entryPoints.http.redirect]
 #    entryPoint = "https"
 # [entryPoints.https]
 # address = ":443"
 #   [entryPoints.https.tls]
  [entryPoints.api]
  address=":8686"
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        users = ["admin:$apr1$8ARUAqfe$/yw6ZI.2MN8M1/IXM7X4y/"]

[acme]
  #mail = "michael.bakker1986@gmail.com"
  #storage = "acme.json"
  #entryPoint = "https"
  #[acme.httpChallenge]
  #  entryPoint = "http"
  #onHostRule = true
  #onDemand = false
  [[acme.domains]]
    main = "www.appmodel.org"

[api]
  entryPoint="api"
  #dashboard = false
  #debug = true
  
#[retry]
  #attempts = 3
  
#[docker]
  # Optional
  # Default: false
  #watch = true
  #exposedByDefault = true
  #usebindportip = true
  # Define a default docker network to use for connections to all containers.
  # Can be overridden by the traefik.docker.network label.
  # Optional
  # network = "web"

# Metrics definition
#[metrics]
#  #...
#
#  # To enable Traefik to export internal metrics to Prometheus
#  [metrics.prometheus]
#
#    # Name of the related entry point
#    #
#    # Optional
#    # Default: "traefik"
#    #
#    entryPoint = "traefik"
#
#    # Buckets for latency metrics
#    #
#    # Optional
#    # Default: [0.1, 0.3, 1.2, 5]
#    #
#    buckets = [0.1,0.3,1.2,5.0]
#
#   # DataDog metrics exporter type
#   [metrics.datadog]
#
#     # DataDog's address.
#     #
#     # Required
#     # Default: "localhost:8125"
#     #
#     address = "localhost:8126"
#
#     # DataDog push interval
#     #
#     # Optional
#     # Default: "10s"
#     #
#     pushInterval = "10s"
#
#    # StatsD metrics exporter type
#  [metrics.statsd]
#
#     # StatD's address.
#     #
#     # Required
#     # Default: "localhost:8125"
#     #
#     address = "localhost:8125"
#
#     # StatD push interval
#     #
#     # Optional
#     # Default: "10s"
#     #
#     pushInterval = "10s"
#
#  # InfluxDB metrics exporter type
#  [metrics.influxdb]
#
#    # InfluxDB's address.
#    #
#    # Required
#    # Default: "localhost:8089"
#    #
#    address = "localhost:8089"
#
#    # InfluxDB's address protocol (udp or http)
#    #
#    # Required
#    # Default: "udp"
#    #
#    protocol = "udp"
#
#    # InfluxDB push interval
#    #
#    # Optional
#    # Default: "10s"
#    #
#    pushinterval = "10s"
#
#    # InfluxDB database used when protocol is http
#    #
#    # Optional
#    # Default: ""
#    #
#    database = ""
#
#    # InfluxDB retention policy used when protocol is http
#    #
#    # Optional
#    # Default: ""
#    #
#    retentionpolicy = ""