# API definition
# Warning: Enabling API will expose Traefik's configuration.
# It is not recommended in production,
# unless secured by authentication and authorizations
defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address=":8686"
      [entryPoints.api.auth.basic]
      users = ["admin:$apr1$8ARUAqfe$/yw6ZI.2MN8M1/IXM7X4y/"]

[acme]
  email = "michael.bakker1986@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  onHostRule = true
  onDemand = false
  [[acme.domains]]
    main = "appmodel.org"

[api]
  entryPoint="api"
  #dashboard = false
  #debug = true
  
#[retry]
  #attempts = 3
  
[docker]
  # Optional
  # Default: false
  watch = true
  exposedByDefault = true
  usebindportip = true
  # Define a default docker network to use for connections to all containers.
  # Can be overridden by the traefik.docker.network label.
  # Optional
  # network = "web"