
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie Model REVISIEMKB v5.10
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 152
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Wed Feb 19 09:59:20 UTC+0100 2014
 */ 


drop table EXPORT_REVISIEMKB;
create table EXPORT_REVISIEMKB(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_REVISIEMKB add Q_ROOT number default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS number default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add FPS_VAR_Woonplaats varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add KvKnummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add GRIDID varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add OprichtingsdatumKvK date default null; 
alter table EXPORT_REVISIEMKB add KlantINGSinds date default null; 
alter table EXPORT_REVISIEMKB add LOO number default null; 
alter table EXPORT_REVISIEMKB add KFRNummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add TweedeKFRNummer varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add KFCBelang number default null; 
alter table EXPORT_REVISIEMKB add KFCBelang_RCK number default null; 
alter table EXPORT_REVISIEMKB add KFCBelang_MK number default null; 
alter table EXPORT_REVISIEMKB add SBF number default null; 
alter table EXPORT_REVISIEMKB add Referentielimiet number default null; 
alter table EXPORT_REVISIEMKB add Branche varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Rechtsvorm varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Vestigingsplaats varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add LinkNaarMeerInformatie varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add ManagementNaam01 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add ManagementLeeftijd01 number default null; 
alter table EXPORT_REVISIEMKB add ManagementNaam02 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add ManagementLeeftijd02 number default null; 
alter table EXPORT_REVISIEMKB add ManagementNaam03 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add ManagementLeeftijd03 number default null; 
alter table EXPORT_REVISIEMKB add Relatienummer1 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager1 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer2 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager2 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer3 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager3 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer4 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager4 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer5 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager5 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer6 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager6 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer7 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager7 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer8 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager8 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer9 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager9 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add Relatienummer10 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add NaamAanvrager10 varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add IMPORT_periode_ultimo date default null; 
alter table EXPORT_REVISIEMKB add OmzetVorig12Mnd number default null; 
alter table EXPORT_REVISIEMKB add OmzetVorig12MndGem number default null; 
alter table EXPORT_REVISIEMKB add OverstandHuidig number default null; 
alter table EXPORT_REVISIEMKB add OverstandAantalDagen number default null; 
alter table EXPORT_REVISIEMKB add OverstandVorigHalfJaar number default null; 
alter table EXPORT_REVISIEMKB add Rating varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add RatingActueel varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add RatingVorigJaar varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add RevisieDatumKOS date default null; 
alter table EXPORT_REVISIEMKB add DekkingswaardeKredietABS number default null; 
alter table EXPORT_REVISIEMKB add DekkingswaardeKrediet number default null; 
alter table EXPORT_REVISIEMKB add AflosschemaAanwezig number default null; 
alter table EXPORT_REVISIEMKB add Faillissement number default null; 
alter table EXPORT_REVISIEMKB add RechtsvormGewijzigd number default null; 
alter table EXPORT_REVISIEMKB add KlantBereikbaar number default null; 
alter table EXPORT_REVISIEMKB add RecenteCijfers number default null; 
alter table EXPORT_REVISIEMKB add GebruikKrediet number default null; 
alter table EXPORT_REVISIEMKB add IsGroeiKlant number default null; 
alter table EXPORT_REVISIEMKB add GroeiklantExtraFinanciering number default null; 
alter table EXPORT_REVISIEMKB add JuistGebruikKrediet number default null; 
alter table EXPORT_REVISIEMKB add INGHuisBankier number default null; 
alter table EXPORT_REVISIEMKB add WilHuisBankierWorden number default null; 
alter table EXPORT_REVISIEMKB add OmzetEisen number default null; 
alter table EXPORT_REVISIEMKB add VooruitzichtBranche number default null; 
alter table EXPORT_REVISIEMKB add AndereEWSSignalen number default null; 
alter table EXPORT_REVISIEMKB add DuidelijkeUitlegKlant number default null; 
alter table EXPORT_REVISIEMKB add InitiatievenKlant number default null; 
alter table EXPORT_REVISIEMKB add VerwachtingKjKlant number default null; 
alter table EXPORT_REVISIEMKB add MeningAccMngr number default null; 
alter table EXPORT_REVISIEMKB add DuidelijkBeeldKlant number default null; 
alter table EXPORT_REVISIEMKB add RenteVerplichting number default null; 
alter table EXPORT_REVISIEMKB add KlantHelpen number default null; 
alter table EXPORT_REVISIEMKB add NettoResultaat number default null; 
alter table EXPORT_REVISIEMKB add PriveOnttrekking number default null; 
alter table EXPORT_REVISIEMKB add Afschrijvingen number default null; 
alter table EXPORT_REVISIEMKB add OperCashflow number default null; 
alter table EXPORT_REVISIEMKB add Aflossingen number default null; 
alter table EXPORT_REVISIEMKB add Vervangingsinvesteringen number default null; 
alter table EXPORT_REVISIEMKB add Dividenduitkeringen number default null; 
alter table EXPORT_REVISIEMKB add Overig number default null; 
alter table EXPORT_REVISIEMKB add NettoCashflow number default null; 
alter table EXPORT_REVISIEMKB add VoldoendeCashflow number default null; 
alter table EXPORT_REVISIEMKB add DEBT number default null; 
alter table EXPORT_REVISIEMKB add EBITDA number default null; 
alter table EXPORT_REVISIEMKB add DSCR number default null; 
alter table EXPORT_REVISIEMKB add ICR number default null; 
alter table EXPORT_REVISIEMKB add CAPEX number default null; 
alter table EXPORT_REVISIEMKB add FinancialStatements number default null; 
alter table EXPORT_REVISIEMKB add VoldoetAanPolicyPaper number default null; 
alter table EXPORT_REVISIEMKB add AfwijkingVoorwaarden number default null; 
alter table EXPORT_REVISIEMKB add ConvenantVoorwaarden number default null; 
alter table EXPORT_REVISIEMKB add ZijnErVeranderingen number default null; 
alter table EXPORT_REVISIEMKB add VeranderingenManagement number default null; 
alter table EXPORT_REVISIEMKB add OnderliggendProbleemPerformanc number default null; 
alter table EXPORT_REVISIEMKB add StructuurRisico number default null; 
alter table EXPORT_REVISIEMKB add StructuurRisicoAcceptabel number default null; 
alter table EXPORT_REVISIEMKB add Organogram number default null; 
alter table EXPORT_REVISIEMKB add Actie01 number default null; 
alter table EXPORT_REVISIEMKB add Actie02 number default null; 
alter table EXPORT_REVISIEMKB add Actie03 number default null; 
alter table EXPORT_REVISIEMKB add Actie04 number default null; 
alter table EXPORT_REVISIEMKB add Actie05 number default null; 
alter table EXPORT_REVISIEMKB add Actie06 number default null; 
alter table EXPORT_REVISIEMKB add Actie07 number default null; 
alter table EXPORT_REVISIEMKB add Actie08 number default null; 
alter table EXPORT_REVISIEMKB add Actie09 number default null; 
alter table EXPORT_REVISIEMKB add Actie10 number default null; 
alter table EXPORT_REVISIEMKB add Actie11 number default null; 
alter table EXPORT_REVISIEMKB add Actie12 number default null; 
alter table EXPORT_REVISIEMKB add Actie13 number default null; 
alter table EXPORT_REVISIEMKB add Actie13B number default null; 
alter table EXPORT_REVISIEMKB add Actie14 number default null; 
alter table EXPORT_REVISIEMKB add Actie15 number default null; 
alter table EXPORT_REVISIEMKB add Actie16 number default null; 
alter table EXPORT_REVISIEMKB add Actie17 number default null; 
alter table EXPORT_REVISIEMKB add Actie17A number default null; 
alter table EXPORT_REVISIEMKB add OrganogramIB number default null; 
alter table EXPORT_REVISIEMKB add CDDCompliant number default null; 
alter table EXPORT_REVISIEMKB add BevoegdhedenGelijkaanKvK number default null; 
alter table EXPORT_REVISIEMKB add CustomerTypeCorrect number default null; 
alter table EXPORT_REVISIEMKB add CustomerSegmentationCorrect number default null; 
alter table EXPORT_REVISIEMKB add CrossReferencesCorrect number default null; 
alter table EXPORT_REVISIEMKB add HighRiskBSKCorrect number default null; 
alter table EXPORT_REVISIEMKB add Fiatteur varchar2(256 char) default null; 
alter table EXPORT_REVISIEMKB add GEASGevuld number default null; 
alter table EXPORT_REVISIEMKB add WKKtovLimietBenoemd number default null; 
alter table EXPORT_REVISIEMKB add Onderdrukdatum number default null; 
alter table EXPORT_REVISIEMKB add BevoegdhedenmatrixCorrect number default null; 

COMMIT;
    
