const log = require('log6')
const bookYearTime = require('../src/XAxis')
const assert = require('assert')
const defaultImport = require('../resources/CustomImport.json')
const TimeAxis = require('../src/TimeAxis')
const monthlyTime = new TimeAxis(defaultImport)
assert.equal(bookYearTime.bkyr.cols.length, 19, 'We use 40columns for now but found' + bookYearTime.bkyr.cols.length)
assert.equal(monthlyTime.detl.cols.length, 252, 'We use 252 detail columns for months ')