const DOCUMENT                  = 'document',
      VALUE                     = 'value',
      VISIBLE                   = 'visible',
      LOCKED                    = 'locked',
      DETAIL_INTERVAL           = 'detl',
      NUMBER                    = 'number',
      STRING_TYPE               = 'string',
      COLUMN                    = 'column',
      TITLE                     = 'title',
      OBJECT_TYPE               = 'object',
      FUNCTION_TYPE             = 'function',
      OUTPUT_NODE_TYPE          = 'Output',
      INPUT_NODE_TYPE           = 'Input',
      DISPLAY_TYPE              = 'displaytype',
      REFERS_TO_PROPERTY_NAME   = 'refersto',
      FFL_VERSION_PROPERTY_NAME = 'ffl_version',
      ENCODING                  = 'utf8'

export {
	DOCUMENT,
	VALUE,
	VISIBLE,
	REFERS_TO_PROPERTY_NAME,
	FFL_VERSION_PROPERTY_NAME,
	DISPLAY_TYPE,
	LOCKED,
	DETAIL_INTERVAL,
	NUMBER,
	COLUMN,
	TITLE,
	OBJECT_TYPE,
	STRING_TYPE,
	FUNCTION_TYPE,
	ENCODING,
	OUTPUT_NODE_TYPE,
	INPUT_NODE_TYPE
}