
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie Model Starter v2.1
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 103
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Wed Nov 20 14:40:36 UTC+0100 2013
 */ 


drop table EXPORT_STARTER;
create table EXPORT_STARTER(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_STARTER add Q_ROOT number default null; 
alter table EXPORT_STARTER add Q_STATUS number default null; 
alter table EXPORT_STARTER add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_STARTER add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_STARTER add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_STARTER add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_STARTER add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_STARTER add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_STARTER add FPS_VAR_Woonplaats varchar2(256 char) default null; 
alter table EXPORT_STARTER add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_STARTER add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_STARTER add OprichtingsdatumKvK date default null; 
alter table EXPORT_STARTER add GevraagdKredietbedrag number default null; 
alter table EXPORT_STARTER add BatchRatingKeuze number default null; 
alter table EXPORT_STARTER add BatchReferentieLimiet number default null; 
alter table EXPORT_STARTER add ToetsAutomatischFiat number default null; 
alter table EXPORT_STARTER add Rechtsvorm number default null; 
alter table EXPORT_STARTER add LooptijdLangerDan10Jaar number default null; 
alter table EXPORT_STARTER add GevestigdInNederland number default null; 
alter table EXPORT_STARTER add BrancheInBusinessRule31 number default null; 
alter table EXPORT_STARTER add INGisHuisbankier number default null; 
alter table EXPORT_STARTER add AantalOverstandenLaatsteHalfJa number default null; 
alter table EXPORT_STARTER add BedrijfsrisicosVerzekerd number default null; 
alter table EXPORT_STARTER add VermeldeCalamiteiten number default null; 
alter table EXPORT_STARTER add PersoonlijkeBorgBestuurderNodi varchar2(256 char) default null; 
alter table EXPORT_STARTER add PersoonlijkeBorgBestuurderBere number default null; 
alter table EXPORT_STARTER add ToetsControleBasisvoorwaarden varchar2(256 char) default null; 
alter table EXPORT_STARTER add AanvullendeCijfersVragen number default null; 
alter table EXPORT_STARTER add RechtsvormBV number default null; 
alter table EXPORT_STARTER add NietGevestigdInNederland number default null; 
alter table EXPORT_STARTER add INGgeenHuisbankier number default null; 
alter table EXPORT_STARTER add TeVeelOverstanden number default null; 
alter table EXPORT_STARTER add BedrijfsrisicosNietVerzekerd number default null; 
alter table EXPORT_STARTER add VermeldeCalamiteitenAanwezig number default null; 
alter table EXPORT_STARTER add ToetsControleBasisvoorwaardenT number default null; 
alter table EXPORT_STARTER add AantalWerknemersFTE number default null; 
alter table EXPORT_STARTER add AantalBestuurdersFTE number default null; 
alter table EXPORT_STARTER add Bestuurders01 varchar2(256 char) default null; 
alter table EXPORT_STARTER add Bestuurders01Gebdatum date default null; 
alter table EXPORT_STARTER add Bestuurders01ErvaringInBranche number default null; 
alter table EXPORT_STARTER add Bestuurders01Opleiding number default null; 
alter table EXPORT_STARTER add Bestuurders02 varchar2(256 char) default null; 
alter table EXPORT_STARTER add Bestuurders02Gebdatum date default null; 
alter table EXPORT_STARTER add Bestuurders02ErvaringInBranche number default null; 
alter table EXPORT_STARTER add Bestuurders02Opleiding number default null; 
alter table EXPORT_STARTER add Bestuurders03 varchar2(256 char) default null; 
alter table EXPORT_STARTER add Bestuurders03Gebdatum date default null; 
alter table EXPORT_STARTER add Bestuurders03ErvaringInBranche number default null; 
alter table EXPORT_STARTER add Bestuurders03Opleiding number default null; 
alter table EXPORT_STARTER add OndernemingProffesioneelBegele number default null; 
alter table EXPORT_STARTER add HoofdredenStartOnderneming number default null; 
alter table EXPORT_STARTER add LeeftijdJongsteBestuurder number default null; 
alter table EXPORT_STARTER add ToetsBestuurders01Gebdatum number default null; 
alter table EXPORT_STARTER add ToetsBestuurders02Gebdatum number default null; 
alter table EXPORT_STARTER add ToetsBestuurders03Gebdatum number default null; 
alter table EXPORT_STARTER add ErvaringMinstErvarenBestuurder number default null; 
alter table EXPORT_STARTER add OpleidingBestuurders number default null; 
alter table EXPORT_STARTER add Investeringsbehoefte number default null; 
alter table EXPORT_STARTER add GestortRisicodragendVermogen number default null; 
alter table EXPORT_STARTER add BenuttingLiqMiddelen number default null; 
alter table EXPORT_STARTER add EigenVermogenVoorKredietverlen number default null; 
alter table EXPORT_STARTER add BalansTotaalNaKredietverlening number default null; 
alter table EXPORT_STARTER add ToetsRisicodragendVermogen varchar2(256 char) default null; 
alter table EXPORT_STARTER add InvesteringImmaterieelActivaNa number default null; 
alter table EXPORT_STARTER add InvesteringMaterieelActivaNaKr number default null; 
alter table EXPORT_STARTER add ProductSluitAanBijInvestering number default null; 
alter table EXPORT_STARTER add GewenstProduct number default null; 
alter table EXPORT_STARTER add NormRisicoVermogenMatVastAkt number default null; 
alter table EXPORT_STARTER add OndernemingAantalOrganisaties number default null; 
alter table EXPORT_STARTER add BrancheSector number default null; 
alter table EXPORT_STARTER add VoortzettingBestaandeActivitei number default null; 
alter table EXPORT_STARTER add BedrijfsadmUitbesteed number default null; 
alter table EXPORT_STARTER add ReedsOmzetGegenereerd number default null; 
alter table EXPORT_STARTER add TussentijdseCijfersAanwezig number default null; 
alter table EXPORT_STARTER add VerwachtResultaatNaBelJaar1 number default null; 
alter table EXPORT_STARTER add VerwachtResultaatNaBelJaar2 number default null; 
alter table EXPORT_STARTER add VerwachtResultaatNaBelJaar3 number default null; 
alter table EXPORT_STARTER add ResultaatNaBelJaar1 number default null; 
alter table EXPORT_STARTER add ResultaatNaBelJaar2 number default null; 
alter table EXPORT_STARTER add VerwachtNettoOmzetJaar1 number default null; 
alter table EXPORT_STARTER add VerwachtNettoOmzetJaar2 number default null; 
alter table EXPORT_STARTER add VerwachtNettoOmzetJaar3 number default null; 
alter table EXPORT_STARTER add VerwachtAfschrijvingenJaar2 number default null; 
alter table EXPORT_STARTER add SolvabiliteitBalansJaar1 number default null; 
alter table EXPORT_STARTER add SolvabiliteitBalansJaar2 number default null; 
alter table EXPORT_STARTER add FinancieleExpert number default null; 
alter table EXPORT_STARTER add EindScore number default null; 
alter table EXPORT_STARTER add TotaalPunten01 number default null; 
alter table EXPORT_STARTER add TotaalPunten02 number default null; 
alter table EXPORT_STARTER add TotaalPunten08 number default null; 
alter table EXPORT_STARTER add TotaalPunten09 number default null; 
alter table EXPORT_STARTER add TotaalPunten10 number default null; 
alter table EXPORT_STARTER add TotaalPunten03 number default null; 
alter table EXPORT_STARTER add TotaalPunten04 number default null; 
alter table EXPORT_STARTER add TotaalPunten05 number default null; 
alter table EXPORT_STARTER add TotaalPunten06 number default null; 
alter table EXPORT_STARTER add TotaalPunten07 number default null; 

COMMIT;
    
