
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie overall 1.0
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 19
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Wed Nov 20 14:38:36 UTC+0100 2013
 */ 


drop table EXPORT_ALL;
create table EXPORT_ALL(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_ALL add Q_STATUS number default null; 
alter table EXPORT_ALL add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_ALL add Q_STATUS_FINAL_BY_NAME varchar2(256 char) default null; 
alter table EXPORT_ALL add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_ALL add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_ALL add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_ALL add Q_STATUS_STARTED_BY_NAME varchar2(256 char) default null; 
alter table EXPORT_ALL add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_ALL add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_ALL add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_ALL add ModelType varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_ALL add FPS_VAR_Woonplaats varchar2(256 char) default null; 

COMMIT;
    
