
/* SQL-script generated by GdetConfigToDB.xsl
 *
 * Target configuration: GDET Configuratie Model INGVerslag v3.9
 * DataSource JNDI mapping: jdbc/FinanDS
 * Maximum string-length: 256
 * Number of tables: 1
 * Number of variables: 103
 *
 * 
 * Target database: Oracle (select another: MySQLOracleMSSQLHSQLDB)
 * - String value set to:  varchar2(undefined char)
 * - Integer value set to:  number(10)
 * - Decimal value set to:  number
 * 
 *
 * Author: A. Samseer
 * Date: Wed Nov 20 14:41:36 UTC+0100 2013
 */ 


drop table EXPORT_FIATDOCUMENT;
create table EXPORT_FIATDOCUMENT(
  id varchar2(256 char) not null,
  DOCUMENTID number(10) not null,
  primary key(id)
);

  
alter table EXPORT_FIATDOCUMENT add AantalKlanten number default null; 
alter table EXPORT_FIATDOCUMENT add AantalLeveranciers number default null; 
alter table EXPORT_FIATDOCUMENT add BatchReferentieLimiet number default null; 
alter table EXPORT_FIATDOCUMENT add BedrijfsadmUitbesteed number default null; 
alter table EXPORT_FIATDOCUMENT add Bedrijfsomzet number default null; 
alter table EXPORT_FIATDOCUMENT add BedrijfsrisicosVerzekerd number default null; 
alter table EXPORT_FIATDOCUMENT add BenuttingLiqMiddelen number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders01 varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders01BSKvraag number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders01ErvaringInBranche number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders01Opleiding number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders02 varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders02BSKvraag number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders02ErvaringInBranche number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders02Opleiding number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders03 varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders03BSKvraag number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders03ErvaringInBranche number default null; 
alter table EXPORT_FIATDOCUMENT add Bestuurders03Opleiding number default null; 
alter table EXPORT_FIATDOCUMENT add BKRCheck number default null; 
alter table EXPORT_FIATDOCUMENT add BrancheOpRestrictedList number default null; 
alter table EXPORT_FIATDOCUMENT add BrancheUitgeslotenBSK number default null; 
alter table EXPORT_FIATDOCUMENT add BSK_Provisie number default null; 
alter table EXPORT_FIATDOCUMENT add BSK_VerhoudingLooptijd number default null; 
alter table EXPORT_FIATDOCUMENT add ContactPersoon varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ControleEigenDeelInvestering number default null; 
alter table EXPORT_FIATDOCUMENT add DekkingDoorHypotheek number default null; 
alter table EXPORT_FIATDOCUMENT add DekkingUitHypotheek number default null; 
alter table EXPORT_FIATDOCUMENT add FinancieleExpert number default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_BIK_CODE varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_BIK_Omschr varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_GridId varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_Housenumber varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_KVKnr varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_Naam varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_Postcode varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add FPS_VAR_Woonplaats varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add GevraagdKredietbedrag number default null; 
alter table EXPORT_FIATDOCUMENT add HoofdredenStartOnderneming number default null; 
alter table EXPORT_FIATDOCUMENT add KFCbelang number default null; 
alter table EXPORT_FIATDOCUMENT add LaatsteNettoOmzet number default null; 
alter table EXPORT_FIATDOCUMENT add Lease number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseBetalingAan number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseBouwjaar number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseBouwMaand number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseEigenMiddelen number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseInruilWaarde number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseInvestering number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseLeverancier varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add LeaseLeverancierRekNr varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add LeaseLooptijdMnd number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseObject number default null; 
alter table EXPORT_FIATDOCUMENT add LeaseSlotTermijn number default null; 
alter table EXPORT_FIATDOCUMENT add LeasObjectBedrag number default null; 
alter table EXPORT_FIATDOCUMENT add MatrixVersion varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ModelVersion varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add NietKredietProductBijING number default null; 
alter table EXPORT_FIATDOCUMENT add OndernemingAantalOrganisaties number default null; 
alter table EXPORT_FIATDOCUMENT add OndernemingProffesioneelBegele number default null; 
alter table EXPORT_FIATDOCUMENT add OprichtingsdatumKvK date default null; 
alter table EXPORT_FIATDOCUMENT add PersoonlijkeBorgBestuurderBere number default null; 
alter table EXPORT_FIATDOCUMENT add Product01_Aflossing number default null; 
alter table EXPORT_FIATDOCUMENT add Product01_Hoofdsom number default null; 
alter table EXPORT_FIATDOCUMENT add Product01_Soort varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Product02_Aflossing number default null; 
alter table EXPORT_FIATDOCUMENT add Product02_Hoofdsom number default null; 
alter table EXPORT_FIATDOCUMENT add Product02_Soort varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Product03_Aflossing number default null; 
alter table EXPORT_FIATDOCUMENT add Product03_Hoofdsom number default null; 
alter table EXPORT_FIATDOCUMENT add Product03_Soort varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Q_ROOT number default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS number default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS_FINAL_BY varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS_FINAL_ON date default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS_MODIFIED_ON date default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS_STARTED_BY varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add Q_STATUS_STARTED_ON date default null; 
alter table EXPORT_FIATDOCUMENT add Rechtsvorm number default null; 
alter table EXPORT_FIATDOCUMENT add ReedsOmzetGegenereerd number default null; 
alter table EXPORT_FIATDOCUMENT add Relatienummer varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add SBICODE2 number default null; 
alter table EXPORT_FIATDOCUMENT add StatusBijKvK number default null; 
alter table EXPORT_FIATDOCUMENT add TelefoonNummer varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add TussentijdseCijfersAanwezig number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_AVA number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_BorgAkte number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_BorgAkte_Bedrag number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_BorgAkte_OnderZ varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_CreditGeld number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_CreditGeld_Bedrag number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HoofdMede number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HoofdMede_OnderZ varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_Bedrag number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_OnderZ varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_TaxatieDatum date default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_TaxatieSoort number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_Voorbelasting number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_VoorbelastingNaam varchar2(256 char) default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_HYP_Waarde number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_OpenVerkl number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_Vordering number default null; 
alter table EXPORT_FIATDOCUMENT add ZKR_Vordering_Bedrag number default null; 

COMMIT;
    
