alter table EXPORT_REVISIEGBI add AflosschemaAanwezig number default null; 
alter table EXPORT_REVISIEGBI add BevoegdhedenGelijkaanKvK number default null; 
alter table EXPORT_REVISIEGBI add CDDCompliant number default null; 
alter table EXPORT_REVISIEGBI add ConvenantVoorwaarden number default null; 
alter table EXPORT_REVISIEGBI add CrossReferencesCorrect number default null; 
alter table EXPORT_REVISIEGBI add CustomerSegmentationCorrect number default null; 
alter table EXPORT_REVISIEGBI add CustomerTypeCorrect number default null; 
alter table EXPORT_REVISIEGBI add EvaluatieIngevuld number default null; 
alter table EXPORT_REVISIEGBI add HighRiskBSKCorrect number default null; 
alter table EXPORT_REVISIEGBI add KFCBelang number default null; 
alter table EXPORT_REVISIEGBI add KFCBelang_MK number default null; 
alter table EXPORT_REVISIEGBI add KFCBelang_RCK number default null; 
alter table EXPORT_REVISIEGBI add OmzetVorig12MndGem number default null; 
alter table EXPORT_REVISIEGBI add OrganogramIB number default null; 
alter table EXPORT_REVISIEGBI add IMPORT_periode_ultimo_start date default null; 
alter table EXPORT_REVISIEGBI add IMPORT_periode_ultimo date default null; 
alter table EXPORT_REVISIEGBI add Referentielimiet number default null; 
alter table EXPORT_REVISIEGBI add StructuurRisicoAcceptabel number default null; 
alter table EXPORT_REVISIEGBI add TelefonischContact number default null; 

COMMIT;