# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        restart: always
        network_mode: host
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lme
        ports:
            - 5432:5432
        expose:
            - 5432

    adminer:
        image: adminer
        restart: always
        network_mode: proxy
        environment:
        ports:
            - 8089:8080
        expose:
            - 8089