# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lme

    adminer:
        image: adminer
        restart: always
        ports:
            - 8089:8080